sudo: false

language: c

compiler:
  - gcc
  - clang

script: mkdir -p build; cd build; cmake --version && cmake .. && make

notifications:
  email: false
  irc:
    channels:
      - "irc.oftc.net#libpredict"
    use_notice: true
    skip_join: true
